baseURL = 'https://heehoposting.xyz/'
languageCode = 'en-us'
title = 'Heehoposting'
theme = 'heehoposting'
pagination.pagerSize = 5

[permalinks]
  posts = '/:year/:month/:title/'

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "blog"

  dateFormat = "2006 January 02"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = false
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']